### PR TITLE
#6137 -- Incoherency: Own Private Stream on Public Streams List 

### PR DESCRIPTION
**Pull request by ben-biddington**
This change ensures that private workstreams are not shown when paging through the lists on "Browse Bettermeans". 
1. go to "Browse Bettermeans"
2. observe that no private workstreams are visible
3. press "..load more..." at the foot of either the "Most Active Public Workstreams" or "Latest Public Workstreams" section
4. once the extra items have loaded, observe that neither section displays private workstreams

See: features/public_work_streams_list.feature
- includes changes that enable webkit as driver for webrat, i.e., ajax interactions are testable
- includes mysql in Gemfile because omission breaks Hash tests

### CODE REVIEW

**Comment by CRabari** [comment]
Thanks Ben- adding in our developer extrordinaire Shereef...

**Comment by ben-biddington** [comment]
Added resolution for bug #7551 (New dash data throws error when the include_subworkstreams parameter is supplied)

**Comment by shereefb** [comment]
Ben, I'm not sure how to do this pull.
It's on a seperate repo, not a seperate branch. And github won't let me auto-pull.

How come?

**Comment by ben-biddington** [comment]
Must have conflicts

**Comment by shereefb** [comment]
can you merge with master?

On Mon, May 2, 2011 at 3:05 PM, ben-biddington <
reply@reply.github.com>wrote:

> Must have conflicts
> 
> On 3 May 2011 10:04, shereefb <
> reply@reply.github.com>wrote:
> 
> > Ben, I'm not sure how to do this pull.
> > It's on a seperate repo, not a seperate branch. And github won't let me
> > auto-pull.
> > 
> > How come?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/Bettermeans/bettermeans/pull/4#issuecomment-1090930
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Bettermeans/bettermeans/pull/4#issuecomment-1090936

## 

we're re-inventing work
check it out www.bettermeans.com

**Comment by ben-biddington** [comment]
I will upmerge to my fork, then you ought to be able to auto merge.

Can't do it just yet though

**Comment by shereefb** [comment]
great. thanks

On Mon, May 2, 2011 at 3:35 PM, ben-biddington <
reply@reply.github.com>wrote:

> I will upmerge to my fork, then you ought to be able to auto merge.
> 
> Can't do it just yet though
> 
> On 3 May 2011 10:26, shereefb <
> reply@reply.github.com>wrote:
> 
> > can you merge with master?
> > 
> > On Mon, May 2, 2011 at 3:05 PM, ben-biddington <
> > reply@reply.github.com>wrote:
> > 
> > > Must have conflicts
> > > 
> > > On 3 May 2011 10:04, shereefb <
> > > reply@reply.github.com>wrote:
> > > 
> > > > Ben, I'm not sure how to do this pull.
> > > > It's on a seperate repo, not a seperate branch. And github won't let
> > > > me
> > > > auto-pull.
> > > > 
> > > > How come?
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > > > 
> > > > https://github.com/Bettermeans/bettermeans/pull/4#issuecomment-1090930
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/Bettermeans/bettermeans/pull/4#issuecomment-1090936
> > 
> > ## 
> > 
> > we're re-inventing work
> > check it out www.bettermeans.com
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/Bettermeans/bettermeans/pull/4#issuecomment-1091033
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Bettermeans/bettermeans/pull/4#issuecomment-1091075

## 

we're re-inventing work
check it out www.bettermeans.com

**Comment by ben-biddington** [comment]
Okay, merge complete. All cucumber features and specs are green.

Can you verify?

<bb />

**Pull request merged**
